# Generated by Django 4.2.6 on 2023-10-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0002_alter_posttag_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posttag',
            table='post_tag',
        ),
    ]
