# Generated by Django 4.2.6 on 2023-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'carmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.CharField(blank=True, max_length=20, null=True)),
                ('lastrequest_time', models.DateTimeField(blank=True, null=True)),
                ('postcity', models.TextField(blank=True, null=True)),
                ('views', models.SmallIntegerField(blank=True, null=True)),
                ('mileage', models.BigIntegerField(blank=True, null=True)),
                ('is_auto', models.BooleanField(blank=True, null=True)),
                ('regodue', models.CharField(blank=True, max_length=20, null=True)),
                ('suburb', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.CharField(blank=True, max_length=300, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('prevprice', models.IntegerField(blank=True, null=True)),
                ('boughtyear', models.SmallIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('fueltype', models.TextField(blank=True, null=True)),
                ('lastservice', models.CharField(blank=True, max_length=20, null=True)),
                ('likes', models.SmallIntegerField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'post_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_private', models.BooleanField(blank=True, null=True)),
                ('userage', models.DateField(blank=True, null=True)),
                ('userimage', models.CharField(blank=True, max_length=300, null=True)),
                ('phones', models.TextField(blank=True, null=True)),
                ('wechats', models.TextField(blank=True, null=True)),
                ('qqs', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('contacts', models.SmallIntegerField(blank=True, null=True)),
                ('reports', models.SmallIntegerField(blank=True, null=True)),
                ('dealerage', models.SmallIntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('dealertitle', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.TextField()),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
    ]
