# Generated by Django 4.2.6 on 2023-10-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posttag',
            table='posttag',
        ),
    ]
